title: Avi's Posts
description: 
theme: minima
author: Avi
markdown: kramdown
minima:
  social_links: []
  # this enables the nav menu
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about"
    - title: "Tags"
      url: "/tags/"


plugins:
  - jekyll-feed
  - jekyll-seo-tag
